# Setup
title:                systemhalted
tagline:             'by Palak Mathur'
description:         'SystemHalted - I am just a DOS error'
url:                 https://systemhalted.in
baseurl:             ''
paginate:            8
permalink:           pretty
disqus_shortname:    palakmathurgithub

# About/contact
author:
  name:              systemhalted
  url:               https://systemhalted.in
  email:             insanethoughts@live.com


markdown: kramdown
highlighter: rouge
# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
# - jekyll-toc

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/

# Custom vars
version:             1.1.0
google_analytics_id: UA-36868278-1

google_site_verification: 1v5ZSlWxFB06EQ-VB5U4n3226XFqq3ki9qusVH2m0K8

feed:
  posts_limit: 50
  
collections_dir: collections
collections:
  jsgames:
    output: false
  emacs: 
    output: true 
  newsletter:
    output: true


sidebar:
  items:
    - title: "Search"
      url: "/search/"
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Kartavya Path - Newsletter"
      url: "/kartavya-path"
    - title: "Featured Posts"
      url: "/featured/"
    - title: "Archives"
      url: "/archives/"
    - title: "Categories"
      url: "/categories/"
    - title: "Tags"
      url: "/tags/"
    - title: "Emacs"
      url: "/emacs/"
    - title: "Javascript Games"
      url: "jsgames/"

    # add / remove / reorder as you like


